language: ruby

sudo: required

services:
  - docker

before_install:
  - docker info
  - docker-compose version
  - docker pull elgalu/selenium

script:
  - docker-compose -f docker-compose.yml up --abort-on-container-exit --build